### ISSUE TITLE
Can not create bug report in NewPipe repository: "An owner of this repository has limited the ability to open an issue to users that have contributed to this repository in the past. "

### ISSUE THREAD

**Issue by selivan** [TeamNewPipe/website#273]
## Exception
* User Action: requested stream
* Request: https://www.youtube.com/watch?v=mJh9qQbdux0
* Content Country: RU
* Content Language: ru
* App Language: en_US
* Service: YouTube
* Version: 0.21.15
* OS: Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
 at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:194)
 at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
 at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
 at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
 at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(Unknown Source:0)
 at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:4)
 at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
 at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
 at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
 at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
 at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
 at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
 at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
 at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:923)

</details>
<hr>

**Comment by selivan** [comment]
Since I am not able to post bug report in NewPipe repository, I posted it here.

"An owner of this repository has limited the ability to open an issue to users that have contributed to this repository in the past. " - this so doesn't make sense.

**Comment by mhmdanas** [comment]
We locked the NewPipe repo temporarily because we had a huge influx of users reporting YouTube videos being broken, even when we already knew of the issue and a fix was underway. Anyway, [0.21.16](https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.21.16) is out with the fix, please upgrade NewPipe.
